parse-dashboard:
  image: yongjhih/parse-dashboard
  links:
    - parse-server
  environment:
    PARSE_SERVER_URL: $PARSE_SERVER_URL
    PARSE_APP_ID: $PARSE_APP_ID
    PARSE_MASTER_KEY: $PARSE_MASTER_KEY
    PARSE_JS_KEY: $PARSE_JS_KEY
    PARSE_REST_KEY: $PARSE_REST_KEY
    PARSE_APP_NAME: $PARSE_APP_NAME
    SERVER_URL: $SERVER_URL
    APP_ID: $APP_ID
    MASTER_KEY: $MASTER_KEY
    APP_NAME: $APP_NAME
    PARSE_DASHBOARD_ALLOW_INSECURE_HTTP: $PARSE_DASHBOARD_ALLOW_INSECURE_HTTP
    USER1: $USER1
    USER1_PASSWORD: $USER1_PASSWORD
    VIRTUAL_HOST: $VIRTUAL_HOST
    LETSENCRYPT_HOST: $LETSENCRYPT_HOST
    LETSENCRYPT_EMAIL: $LETSENCRYPT_EMAIL
  ports:
    - "4040:4040"
#  volumes:
#    - "parse-dashboard-config.json:/src/Parse-Dashboard/parse-dashboard-config.json"

nginx:
  image: nginx
  container_name: nginx
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - "/etc/nginx/conf.d"
    - "/etc/nginx/vhost.d"
    - "/usr/share/nginx/html"
    - "./volumes/proxy/certs:/etc/nginx/certs:ro"
nginx-gen:
  image: jwilder/docker-gen
  container_name: nginx-gen
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock:ro"
    - "./volumes/proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
  volumes_from:
    - nginx
  entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
letsencrypt-nginx-proxy-companion:
  image: jrcs/letsencrypt-nginx-proxy-companion
  container_name: letsencrypt-nginx-proxy-companion
  volumes_from:
    - nginx
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    - "./volumes/proxy/certs:/etc/nginx/certs:rw"
  environment:
    - NGINX_DOCKER_GEN_CONTAINER=nginx-gen

# vim:set et ts=2 sw=2:
