parse-dashboard:
  #build: .
  image: yongjhih/parse-dashboard
  environment:
    SERVER_URL: $SERVER_URL
    APP_ID: $APP_ID
    MASTER_KEY: $MASTER_KEY
    APP_NAME: $APP_NAME
    ALLOW_INSECURE_HTTP: $PARSE_DASHBOARD_ALLOW_INSECURE_HTTP
    USER1: $USER1
    USER1_PASSWORD: $USER1_PASSWORD
    PARSE_DASHBOARD_ALLOW_INSECURE_HTTP: $PARSE_DASHBOARD_ALLOW_INSECURE_HTTP
    PARSE_DASHBOARD_SERVER_URL: $SERVER_URL
    PARSE_DASHBOARD_MASTER_KEY: $MASTER_KEY
    PARSE_DASHBOARD_APP_ID: $APP_ID
    PARSE_DASHBOARD_APP_NAME: $APP_NAME
    PARSE_DASHBOARD_USER_ID: $USER1
    PARSE_DASHBOARD_USER_PASSWORD: $USER1_PASSWORD
    PARSE_DASHBOARD_CONFIG: $PARSE_DASHBOARD_CONFIG
    MOUNT_PATH: $PARSE_DASHBOARD_MOUNT_PATH

    PORT: 4040
  ports:
    - "4040:4040"

# vim:set et ts=2 sw=2:
